#include "instructions.h"

void nop(Frame &frame) {}
void aconst_null(Frame &frame) {}
void iconst_m1(Frame &frame) {}
void iconst_0(Frame &frame) {}
void iconst_1(Frame &frame) {}
void iconst_2(Frame &frame) {}
void iconst_3(Frame &frame) {}
void iconst_4(Frame &frame) {}
void iconst_5(Frame &frame) {}
void lconst_0(Frame &frame) {}
void lconst_1(Frame &frame) {}
void fconst_0(Frame &frame) {}
void fconst_1(Frame &frame) {}
void fconst_2(Frame &frame) {}
void dconst_0(Frame &frame) {}
void dconst_1(Frame &frame) {}

void bipush(Frame &frame) {
    printf("bipush\n");
    frame.pc++;
}

void sipush(Frame &frame) {}
void ldc(Frame &frame) {}
void ldc_w(Frame &frame) {}
void ldc2_w(Frame &frame) {}
void iload(Frame &frame) {}
void lload(Frame &frame) {}
void fload(Frame &frame) {}
void dload(Frame &frame) {}
void aload(Frame &frame) {}
void iload_0(Frame &frame) {}
void iload_1(Frame &frame) {}
void iload_2(Frame &frame) {}
void iload_3(Frame &frame) {}
void lload_0(Frame &frame) {}
void lload_1(Frame &frame) {}
void lload_2(Frame &frame) {}
void lload_3(Frame &frame) {}
void fload_0(Frame &frame) {}
void fload_1(Frame &frame) {}
void fload_2(Frame &frame) {}
void fload_3(Frame &frame) {}
void dload_0(Frame &frame) {}
void dload_1(Frame &frame) {}
void dload_2(Frame &frame) {}
void dload_3(Frame &frame) {}
void aload_0(Frame &frame) {}
void aload_1(Frame &frame) {}
void aload_2(Frame &frame) {}
void aload_3(Frame &frame) {}
void iaload(Frame &frame) {}
void laload(Frame &frame) {}
void faload(Frame &frame) {}
void daload(Frame &frame) {}
void aaload(Frame &frame) {}
void baload(Frame &frame) {}
void caload(Frame &frame) {}
void saload(Frame &frame) {}
void istore(Frame &frame) {}
void lstore(Frame &frame) {}
void fstore(Frame &frame) {}
void dstore(Frame &frame) {}
void astore(Frame &frame) {}
void istore_0(Frame &frame) {}
void istore_1(Frame &frame) {}
void istore_2(Frame &frame) {}
void istore_3(Frame &frame) {}
void lstore_0(Frame &frame) {}
void lstore_1(Frame &frame) {}
void lstore_2(Frame &frame) {}
void lstore_3(Frame &frame) {}
void fstore_0(Frame &frame) {}
void fstore_1(Frame &frame) {}
void fstore_2(Frame &frame) {}
void fstore_3(Frame &frame) {}
void dstore_0(Frame &frame) {}
void dstore_1(Frame &frame) {}
void dstore_2(Frame &frame) {}
void dstore_3(Frame &frame) {}
void astore_0(Frame &frame) {}
void astore_1(Frame &frame) {}
void astore_2(Frame &frame) {}
void astore_3(Frame &frame) {}
void iastore(Frame &frame) {}
void lastore(Frame &frame) {}
void fastore(Frame &frame) {}
void dastore(Frame &frame) {}
void aastore(Frame &frame) {}
void bastore(Frame &frame) {}
void castore(Frame &frame) {}
void sastore(Frame &frame) {}
void pop(Frame &frame) {}
void pop2(Frame &frame) {}
void dup(Frame &frame) {}
void dup_x1(Frame &frame) {}
void dup_x2(Frame &frame) {}
void dup2(Frame &frame) {}
void dup2_x1(Frame &frame) {}
void dup2_x2(Frame &frame) {}
void swap(Frame &frame) {}
void iadd(Frame &frame) {}
void ladd(Frame &frame) {}
void fadd(Frame &frame) {}
void dadd(Frame &frame) {}
void isub(Frame &frame) {}
void lsub(Frame &frame) {}
void fsub(Frame &frame) {}
void dsub(Frame &frame) {}
void imul(Frame &frame) {}
void lmul(Frame &frame) {}
void fmul(Frame &frame) {}
void dmul(Frame &frame) {}
void idiv(Frame &frame) {}
void ldiv(Frame &frame) {}
void fdiv(Frame &frame) {}
void ddiv(Frame &frame) {}
void irem(Frame &frame) {}
void lrem(Frame &frame) {}
void frem(Frame &frame) {}
void drem(Frame &frame) {}
void ineg(Frame &frame) {}
void lneg(Frame &frame) {}
void fneg(Frame &frame) {}
void dneg(Frame &frame) {}
void ishl(Frame &frame) {}
void lshl(Frame &frame) {}
void ishr(Frame &frame) {}
void lshr(Frame &frame) {}
void iushr(Frame &frame) {}
void lushr(Frame &frame) {}
void iand(Frame &frame) {}
void land(Frame &frame) {}
void ior(Frame &frame) {}
void lor(Frame &frame) {}
void ixor(Frame &frame) {}
void lxor(Frame &frame) {}
void iinc(Frame &frame) {}
void i2l(Frame &frame) {}
void i2f(Frame &frame) {}
void i2d(Frame &frame) {}
void l2i(Frame &frame) {}
void l2f(Frame &frame) {}
void l2d(Frame &frame) {}
void f2i(Frame &frame) {}
void f2l(Frame &frame) {}
void f2d(Frame &frame) {}
void d2i(Frame &frame) {}
void d2l(Frame &frame) {}
void d2f(Frame &frame) {}
void i2b(Frame &frame) {}
void i2c(Frame &frame) {}
void i2s(Frame &frame) {}
void lcmp(Frame &frame) {}
void fcmpl(Frame &frame) {}
void fcmpg(Frame &frame) {}
void dcmpl(Frame &frame) {}
void dcmpg(Frame &frame) {}
void ifeq(Frame &frame) {}
void ifne(Frame &frame) {}
void iflt(Frame &frame) {}
void ifge(Frame &frame) {}
void ifgt(Frame &frame) {}
void ifle(Frame &frame) {}
void if_icmpeq(Frame &frame) {}
void if_icmpne(Frame &frame) {}
void if_icmplt(Frame &frame) {}
void if_icmpge(Frame &frame) {}
void if_icmpgt(Frame &frame) {}
void if_icmple(Frame &frame) {}
void if_acmpeq(Frame &frame) {}
void if_acmpne(Frame &frame) {}
void c_goto(Frame &frame) {}
void jsr(Frame &frame) {}
void ret(Frame &frame) {}
void tableswitch(Frame &frame) {}
void lookupswitch(Frame &frame) {}
void ireturn(Frame &frame) {}
void lreturn(Frame &frame) {}
void freturn(Frame &frame) {}
void dreturn(Frame &frame) {}
void areturn(Frame &frame) {}
void c_return(Frame &frame) {}
void getstatic(Frame &frame) {}
void putstatic(Frame &frame) {}
void getfield(Frame &frame) {}
void putfield(Frame &frame) {}
void invokevirtual(Frame &frame) {}
void invokespecial(Frame &frame) {}
void invokestatic(Frame &frame) {}
void invokeinterface(Frame &frame) {}
void invokedynamic(Frame &frame) {}
void c_new(Frame &frame) {}
void newarray(Frame &frame) {}
void anewarray(Frame &frame) {}
void arraylength(Frame &frame) {}
void athrow(Frame &frame) {}
void checkcast(Frame &frame) {}
void instanceof (Frame & frame) {}
void monitorenter(Frame &frame) {}
void monitorexit(Frame &frame) {}
void wide(Frame &frame) {}
void multianewarray(Frame &frame) {}
void ifnull(Frame &frame) {}
void ifnonnull(Frame &frame) {}
void goto_w(Frame &frame) {}
void jsr_w(Frame &frame) {}